from enum import Enum, auto


class AgentName(Enum):
    gekko = "Gekko"
    fade = "Fade"
    breach = "Breach"
    deadlock = "Deadlock"
    tejo = "Tejo"
    raze = "Raze"
    chamber = "Chamber"
    kayo = "KAY/O"
    skye = "Skye"
    cypher = "Cypher"
    sova = "Sova"
    killjoy = "Killjoy"
    harbor = "Harbor"
    vyse = "Vyse"
    viper = "Viper"
    veto = "Veto"
    phoenix = "Phoenix"
    astra = "Astra"
    brimstone = "Brimstone"
    iso = "Iso"
    clove = "Clove"
    neon = "Neon"
    yoru = "Yoru"
    waylay = "Waylay"
    sage = "Sage"
    reyna = "Reyna"
    omen = "Omen"
    jett = "Jett"
    miks = "Miks"
